### ISSUE TITLE
Identify or flag in some way sw-solr-tests tests that are specifically relevancy-related use cases

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sw_index_tests#170]
MVP: For existing tests that related to relevance changes, ability to filter those tests (possibly only run that subset)

Have this already with JIRA tags? Should be JIRA SW Feedback Jira tickets related.

**Comment by cbeer** [comment]
Perhaps it's enough to run `rspec -t jira` to run the JIRA-ticket-tagged tests?

**Comment by shelleydoljack** [comment]
I think most of the jira-tagged tests will be relevancy-related use cases.

**Comment by cmh2166** [comment]
No longer needed; too confusing for team to unwrap for limited ROI in this work cycle.
