### ISSUE TITLE
Investigate sources solr failed responses for sw-dev

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sw_index_tests#173]
https://sul-ci-prod.stanford.edu/blue/rest/organizations/jenkins/pipelines/SUL-DLSS/pipelines/sw_index_tests/branches/test-sw-dev-sul-solr/runs/10/nodes/17/log/?start=0

Log file `#151` & `#152`

**Comment by mejackreed** [comment]
These are timeouts due to long returning queries. These pass locally at the moment, and I think it could just be a network / solr capacity issue.

Closing for now, we can increase timeout later if need be.
