### ISSUE TITLE
JIRA tickets without relevancy tests yet

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/sw_index_tests#174]
Get list of JIRA tickets since last one linked to test (2013) that don’t have tests yet, assess effort to make tests for these.

**Comment by ahafele** [comment]
[Here they are. I didn't make any judgement calls about if/how much we care about these](https://jirasul.stanford.edu/jira/issues/?jql=project%20in%20(SW%2C%20VUF)%20AND%20labels%20%3D%20relevancy)


FYI - [here are a bunch of CJK related tickets that might be of interest at some point ](https://jirasul.stanford.edu/jira/issues/?jql=project%20in%20(VUF%2C%20SW)%20AND%20text%20~%20%22CJK%20testing%22)

**Comment by shelleydoljack** [comment]
Issues created from the 13 jira tickets Alissa identified.
