### ISSUE TITLE
Fix regression in katakana recall

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sw_index_tests#212]
I think 2 separate problems have been noted:

1) We do weird tokenization with mixed katakana/kanji metadata or queries. We end up uni/bigramming the katakana, which probably makes no sense at all (and I'll double-check this.)

2) Now that we're not blindly uni/bigramming katakana, we should pay attention to stemming rules to strip out grammatical indicators.

**Comment by mejackreed** [comment]
https://github.com/sul-dlss/sw_index_tests/blob/master/spec/cjk/japanese_series_spec.rb#L7-L10
